"""Deterministic facts about the drawing, straight out of `circuit_logic.json`.

This endpoint costs nothing, is instant, and is exactly repeatable — and it answers §12
Q21–Q25 and Q64 outright, before anyone spends a token. That is the whole thesis of
`webui_ideas.md` §4 in one file: **a good version of this application answers as many
questions as possible with ordinary code and saves the model for what only it can do.**

It is also the natural home for the deterministic tabs that come next (net explorer, tables,
BOM), which is why the loader exposes the parsed document rather than only the summary.
"""

from __future__ import annotations

import json
import re
from collections import Counter
from functools import lru_cache
from pathlib import Path
from typing import Any

from .locations import Spot, resolve_geometry

#: The one fact about this drawing that a careful reader still gets wrong. The title block
#: has no revision field; the `D` in the side tab and the SIZE box is the sheet size. §12 Q21
#: exists purely to catch it, so we say it out loud on the front page rather than waiting to
#: be asked.
REVISION_NOTE = "Revision: none — the 'D' in the title block is the sheet size, not a revision."

#: A tile filename is generated by the extraction skill (`tile_r1c1.png`), but it reaches this
#: module from the URL, so it is treated as untrusted regardless. Names are additionally
#: checked against the manifest before anything is opened.
TILE_NAME = re.compile(r"^[A-Za-z0-9._-]{1,64}\.png$")


class DrawingUnavailable(RuntimeError):
    pass


@lru_cache(maxsize=8)
def load_circuit_logic(drawing_dir: Path) -> dict[str, Any]:
    path = drawing_dir / "circuit_logic.json"
    try:
        return json.loads(path.read_text("utf-8"))
    except FileNotFoundError as exc:
        raise DrawingUnavailable(f"no circuit_logic.json in {drawing_dir}") from exc
    except json.JSONDecodeError as exc:
        raise DrawingUnavailable(f"circuit_logic.json is not valid JSON: {exc}") from exc


def drawing_summary(drawing_dir: Path) -> dict[str, Any]:
    doc = load_circuit_logic(drawing_dir)
    meta = doc.get("drawing") or {}
    relationships = doc.get("relationships") or []

    return {
        "drawing_number": meta.get("drawing_number"),
        "title": meta.get("title"),
        "assembly": meta.get("assembly"),
        "date": meta.get("date"),
        "revision": meta.get("revision"),
        "revision_note": REVISION_NOTE if not meta.get("revision") else None,
        "proprietary_notice": meta.get("proprietary_notice"),
        "notes": meta.get("notes") or [],
        "references": meta.get("references") or [],
        "counts": {
            "components": len(doc.get("components") or []),
            "terminals": len(doc.get("terminals") or []),
            "nets": len(doc.get("nets") or []),
            "wires": len(doc.get("wires") or []),
            "cables": len(doc.get("cables") or []),
            "subsystems": len(doc.get("subsystems") or []),
            "relationships": len(relationships),
        },
        "subsystems": [
            {
                "id": s.get("id"),
                "description": s.get("description"),
                "members": len(s.get("member_components") or []),
            }
            for s in (doc.get("subsystems") or [])
        ],
        "component_classes": dict(
            sorted(Counter(c.get("class") for c in (doc.get("components") or [])).items())
        ),
        "relationship_types": dict(
            sorted(Counter(r.get("type") for r in relationships).items())
        ),
        "artifacts": _artifacts(drawing_dir),
        "source": _source_meta(drawing_dir),
        "tiles": tile_manifest(drawing_dir),
    }


# Which identifiers the extraction invented. This is the table in `prompts.py` under "Names
# that are not on the drawing", in code — **the two say the same thing and must change
# together.** The model is made to put these in parentheses after a description because the
# reader is holding the sheet and cannot find them on it; the UI marks them for the same
# reason, so that a clickable citation never implies a label that is not there.
#
# Component ids are not in that table and are therefore treated as printed. Everything else
# below is a *shape*, not a list of ids: which ids exist stays in `circuit_logic.json`.

#: Every `W###`. The sheet labels runs by colour, gauge and net, never by a number.
WIRE_IDS_ARE_OURS = True
#: `TB-…:<n>` — the block is usually marked, the point numbers are assigned in drawing order.
INVENTED_TERMINAL_PREFIX = "TB-"
#: Connector pin numbers, inferred rather than printed (inference 1 in `EXTRACTION_NOTES.md`).
INVENTED_TERMINAL_PARENTS = ("RECEPT1", "INFEED1", "DISCHARGE1")
#: `NET-PB1` is printed as `PB1`; renamed during extraction to avoid colliding with the
#: push-button component of that name.
INVENTED_NET_PREFIX = "NET-"


def designator_index(drawing_dir: Path) -> dict[str, Any]:
    """Every identifier an answer can cite, with somewhere on the sheet to point at.

    This is what makes a citation clickable. An answer is prose, and the *only* safe way to
    decide which of its backticked spans are real identifiers is to look them up in a list the
    server derived from `circuit_logic.json` — never by pattern-matching model output. So this
    endpoint is that list, and the client's rule is an exact, case-folded allowlist lookup.

    It is also the pan target, and every point below comes from `resolve_geometry()` — which
    layers the human-authored `locations.json` over the vision-pass estimate the netlist has
    always carried. In precedence order:

    - a **terminal** with its own placed point uses it;
    - otherwise the **site** that claims that pin — this is what puts `CR-SW:14` on the contact
      block instead of `CR-SW`'s coil eight inches away;
    - otherwise its **parent component's** point, flagged `placement: "parent"` so the viewer can
      admit it is showing the component and not the pin;
    - a **component** is all of its sites, so a relay drawn in three places has three points and a
      `rect` that frames them all;
    - a **wire** is its two terminals and a **net** is every terminal on it, so `rect` frames the
      run rather than the components it happens to pass through. Neither is ever *placed*: their
      geometry is their endpoints', which is why placing 131 terminals gives 71 wires their
      positions for free.

    `point` is the centre of `rect`; `rect` is what the viewer frames; `places` is every distinct
    place the id is drawn — each with its own point, site name and `placement` — and is present
    **only when there are two or more**. 269 of 275 entries on this drawing are a single point, and
    duplicating that into a second field would grow the payload for nothing, so a client reads
    `places` if it is there and falls back to `point` if it is not. All of it is in PDF points —
    the same space as `tiles[].pdf_rect` and every bbox in `geometry.json` — so the browser needs
    no registration step. Any of it may be `null`: six components (the two off-page machines and
    the four referenced drawings) have no location, and a citation that reaches only those is
    legitimate with nowhere to fly to.

    `placement` travels with components and terminals because the viewer draws them, and a marker
    has to be able to say how much it knows: `confirmed` (a person placed it, in the Locate
    editor), `seed` (the extraction's own vision estimate, good to about 11 pt on this sheet and
    occasionally a whole conductor row out), or `parent`. There is no fourth, because nothing
    derives — see `locations.py`.

    Deliberately uncached and deliberately not part of `/api/drawing`: it is a few hundred
    dictionary lookups over two already-cached parses, and keeping it separate means a client that
    fails to load it loses clickable citations and nothing else.
    """
    doc = load_circuit_logic(drawing_dir)
    components = [c for c in (doc.get("components") or []) if isinstance(c, dict)]
    terminals = [t for t in (doc.get("terminals") or []) if isinstance(t, dict)]

    manifest = tile_manifest(drawing_dir)
    geometry = resolve_geometry(drawing_dir, doc, manifest["page_size_pt"] if manifest else None)
    parent = {t.get("id"): t.get("parent_component") for t in terminals}

    entries: list[dict[str, Any]] = []

    for component in components:
        cid = component.get("id")
        if not isinstance(cid, str):
            continue
        entries.append(
            _entry(
                cid,
                "component",
                _component_label(component),
                [cid],
                geometry.component(cid),
                on_sheet=True,
                aliases=[a for a in (component.get("aliases") or []) if isinstance(a, str)],
            )
        )

    for terminal in terminals:
        tid = terminal.get("id")
        if not isinstance(tid, str):
            continue
        owner = terminal.get("parent_component")
        entries.append(
            _entry(
                tid,
                "terminal",
                _terminal_label(terminal),
                [owner] if isinstance(owner, str) else [],
                [geometry.terminal(tid)],
                on_sheet=not _invented_terminal(owner),
            )
        )

    for net in doc.get("nets") or []:
        nid = net.get("id") if isinstance(net, dict) else None
        if not isinstance(nid, str):
            continue
        pins = [t for t in (net.get("member_terminals") or []) if isinstance(t, str)]
        entries.append(
            _entry(
                nid,
                "net",
                _net_label(net),
                [parent.get(t) for t in pins],
                [geometry.terminal(t) for t in pins],
                on_sheet=not nid.startswith(INVENTED_NET_PREFIX),
                with_placement=False,
                label_at=geometry.label(nid),
            )
        )

    for wire in doc.get("wires") or []:
        wid = wire.get("id") if isinstance(wire, dict) else None
        if not isinstance(wid, str):
            continue
        ends = [wire.get("from_terminal"), wire.get("to_terminal")]
        entries.append(
            _entry(
                wid,
                "wire",
                _wire_label(wire),
                [parent.get(t) for t in ends],
                [geometry.terminal(t) if isinstance(t, str) else None for t in ends],
                on_sheet=not WIRE_IDS_ARE_OURS,
                with_placement=False,
                label_at=geometry.label(wid),
            )
        )

    return {
        "drawing_number": (doc.get("drawing") or {}).get("drawing_number"),
        "counts": dict(Counter(e["kind"] for e in entries)),
        "located": sum(1 for e in entries if e["point"]),
        "locations": geometry.report(),
        "entries": entries,
    }


def _entry(
    identifier: str,
    kind: str,
    label: str,
    members: list[Any],
    placed: list[Spot | None],
    *,
    on_sheet: bool,
    aliases: list[str] | None = None,
    with_placement: bool = True,
    label_at: Spot | None = None,
) -> dict[str, Any]:
    """One row of the index.

    `members` are the components it is drawn through — deduplicated in order, kept whether or not
    they have a location, because the overlay rings the ones it can place and the popover still
    names the rest. `placed` is the geometry, already resolved, in the order the caller wants it
    shown: the first one is the primary, which is what `placement` describes.

    `label_at` is for wires and nets only, and is **not** geometry: `rect` still frames the run
    from its endpoints. It is where the name is printed on the sheet, so a citation of `W048` can
    land on the text instead of on the midpoint of a rectangle. Absent until a person places it.
    """
    seen: list[str] = []
    for member in members:
        if isinstance(member, str) and member not in seen:
            seen.append(member)

    found = [p for p in placed if p is not None]
    places: list[dict[str, Any]] = []
    for p in found:
        place: dict[str, Any] = {"point": [p.point[0], p.point[1]], "placement": p.placement}
        if p.site:
            place["site"] = p.site
        # Which side of the dot the id is written on. Omitted far more often than not, and the
        # viewer's default is east, so this only appears where a human moved one out of the way.
        if p.label_dir:
            place["label_dir"] = p.label_dir
        # Deduplicated whole, not by coordinate: two terminals of a net at the same site are one
        # dot, but the same point reached with different provenance is worth keeping apart.
        if place not in places:
            places.append(place)

    points = [place["point"] for place in places]
    rect = (
        [
            min(x for x, _ in points),
            min(y for _, y in points),
            max(x for x, _ in points),
            max(y for _, y in points),
        ]
        if points
        else None
    )
    entry: dict[str, Any] = {
        "id": identifier,
        "kind": kind,
        "label": label,
        "on_sheet": on_sheet,
        "members": seen,
        "point": [(rect[0] + rect[2]) / 2, (rect[1] + rect[3]) / 2] if rect else None,
        "rect": rect,
    }
    # Only when it says something `point` does not: see the docstring above on payload size.
    if len(places) > 1:
        entry["places"] = places
    if with_placement:
        entry["placement"] = found[0].placement if found else None
    if label_at is not None:
        entry["label_point"] = [label_at.point[0], label_at.point[1]]
        if label_at.label_dir:
            entry["label_dir"] = label_at.label_dir
    if aliases:
        entry["aliases"] = aliases
    return entry


def _invented_terminal(owner: Any) -> bool:
    return isinstance(owner, str) and (
        owner.startswith(INVENTED_TERMINAL_PREFIX) or owner in INVENTED_TERMINAL_PARENTS
    )


def _component_label(component: dict[str, Any]) -> str:
    kind = str(component.get("class") or "component").replace("_", " ")
    return f"{kind} — {component.get('description') or component.get('function') or ''}".strip(
        " —"
    )


def _terminal_label(terminal: dict[str, Any]) -> str:
    function = terminal.get("function")
    net = terminal.get("net")
    parts = [f"{function} terminal" if function else "terminal"]
    if terminal.get("parent_component"):
        parts.append(f"on {terminal['parent_component']}")
    if net:
        parts.append(f", net {net}")
    return " ".join(parts).replace(" ,", ",")


def _net_label(net: dict[str, Any]) -> str:
    head = " ".join(str(v) for v in (net.get("signal_type"), net.get("nominal_voltage")) if v)
    terminals = len(net.get("member_terminals") or [])
    # Terminals, not wires — the counting trap `prompts.py` warns about. Say which one it is.
    return f"{head or 'net'}, {terminals} terminal{'' if terminals == 1 else 's'}"


def _wire_label(wire: dict[str, Any]) -> str:
    head = " ".join(str(v) for v in (wire.get("color"), wire.get("gauge")) if v)
    ends = f"{wire.get('from_terminal')} → {wire.get('to_terminal')}"
    return f"{head} wire, {ends}" if head else f"wire, {ends}"


def tile_manifest(drawing_dir: Path) -> dict[str, Any] | None:
    """The rendered raster of the sheet, normalised for a browser.

    `tiles/tiles.json` is written by the extraction skill and already carries everything a
    viewer needs: the page size, the DPI, and for each tile its rectangle **in PDF points**
    plus its pixel dimensions. Those points are the one coordinate system this project has —
    `components[].location` and every bbox in `geometry.json` live in the same space — so the
    rectangles are passed through unconverted and the browser does the single multiplication
    (`px = pt × dpi/72`). That is what will let a component overlay land on the drawing later
    with no registration step.

    Returns `None` unless the manifest parses, declares a positive page size, and names at
    least one PNG that is actually on disk. A half-rendered tile directory has to mean "no
    viewer", not "a viewer full of broken images".

    Deliberately uncached: it is a 4 KB parse plus one `stat` per tile, it is read once per
    page load and once per tile fetch, and a cache here would hand a stale `None` to anyone
    who renders tiles while the server is up.
    """
    tiles_dir = drawing_dir / "tiles"
    try:
        manifest = json.loads((tiles_dir / "tiles.json").read_text("utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(manifest, dict):
        return None

    size = _pair(manifest.get("page_size"))
    if size is None or size[0] <= 0 or size[1] <= 0:
        return None

    tiles = [t for t in (_tile(e, tiles_dir) for e in manifest.get("tiles") or []) if t]
    if not tiles:
        return None

    grid = manifest.get("grid") if isinstance(manifest.get("grid"), dict) else {}
    return {
        "page_size_pt": list(size),
        "dpi": manifest.get("dpi"),
        "rows": grid.get("rows"),
        "cols": grid.get("cols"),
        "count": len(tiles),
        "tiles": tiles,
    }


def tile_file(drawing_dir: Path, name: str) -> Path | None:
    """Resolve one tile by name — but only a name the manifest itself lists.

    The manifest is the allowlist. Pattern-matching the filename would already stop traversal;
    requiring the name to be a tile we published stops everything else too.
    """
    if not TILE_NAME.match(name):
        return None
    manifest = tile_manifest(drawing_dir)
    if manifest is None or not any(t["file"] == name for t in manifest["tiles"]):
        return None
    path = drawing_dir / "tiles" / name
    return path if path.is_file() else None


def _tile(entry: Any, tiles_dir: Path) -> dict[str, Any] | None:
    if not isinstance(entry, dict):
        return None
    name = entry.get("file")
    if not isinstance(name, str) or not TILE_NAME.match(name):
        return None
    if not (tiles_dir / name).is_file():
        return None

    rect = entry.get("pdf_rect")
    if not isinstance(rect, list) or len(rect) != 4:
        return None
    try:
        x0, y0, x1, y1 = (float(v) for v in rect)
    except (TypeError, ValueError):
        return None
    if x1 <= x0 or y1 <= y0:
        return None

    return {
        "file": name,
        "row": entry.get("row"),
        "col": entry.get("col"),
        "pdf_rect": [x0, y0, x1, y1],
        "pixels": _pair(entry.get("pixels")),
    }


def _pair(value: Any) -> tuple[float, float] | None:
    if not isinstance(value, list) or len(value) != 2:
        return None
    try:
        return float(value[0]), float(value[1])
    except (TypeError, ValueError):
        return None


def source_document(drawing_dir: Path) -> Path | None:
    """The PDF the netlist was extracted from, or `None` if it is not beside the extraction.

    Every extraction has the shape `<drawing>/source_docs/*.pdf` next to
    `<drawing>/extracted_docs/`, and `tiles/tiles.json` already records which file in there was
    rendered — so that name is the first choice, the drawing number is the second, and a lone
    PDF is the third. With several unrelated PDFs and nothing to disambiguate them (which is
    the state of `ModLinx/source_docs/`), this returns `None` rather than guessing.
    """
    source_dir = drawing_dir.parent / "source_docs"
    if not source_dir.is_dir():
        return None
    pdfs = sorted(p for p in source_dir.glob("*.pdf") if p.is_file())
    if not pdfs:
        return None

    for name in (_tiles_source_name(drawing_dir), _drawing_number(drawing_dir)):
        if not name:
            continue
        stem = Path(name).stem
        for pdf in pdfs:
            if pdf.stem == stem:
                return pdf
    return pdfs[0] if len(pdfs) == 1 else None


def _source_meta(drawing_dir: Path) -> dict[str, Any] | None:
    path = source_document(drawing_dir)
    if path is None:
        return None
    return {"name": path.name, "bytes": path.stat().st_size, "media_type": "application/pdf"}


def _tiles_source_name(drawing_dir: Path) -> str | None:
    try:
        manifest = json.loads((drawing_dir / "tiles" / "tiles.json").read_text("utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    name = manifest.get("source_file")
    return name if isinstance(name, str) else None


def _drawing_number(drawing_dir: Path) -> str | None:
    try:
        meta = load_circuit_logic(drawing_dir).get("drawing") or {}
    except DrawingUnavailable:
        return None
    number = meta.get("drawing_number")
    return number if isinstance(number, str) else None


def _artifacts(drawing_dir: Path) -> list[dict[str, Any]]:
    """What the model can actually see, with sizes. Shown in the UI because "which files did
    it read?" is the first question anyone sensible asks about an answer like this."""
    out = []
    for name in ("EXTRACTION_NOTES.md", "circuit_logic.json", "custom_kg.json", "geometry.json"):
        path = drawing_dir / name
        if path.exists():
            out.append({"name": name, "bytes": path.stat().st_size})
    return out
