"""Deterministic facts about the drawing, straight out of `circuit_logic.json`.

This endpoint costs nothing, is instant, and is exactly repeatable — and it answers §12
Q21–Q25 and Q64 outright, before anyone spends a token. That is the whole thesis of
`webui_ideas.md` §4 in one file: **a good version of this application answers as many
questions as possible with ordinary code and saves the model for what only it can do.**

It is also the natural home for the deterministic tabs that come next (net explorer, tables,
BOM), which is why the loader exposes the parsed document rather than only the summary.
"""

from __future__ import annotations

import json
import re
from collections import Counter
from functools import lru_cache
from pathlib import Path
from typing import Any

#: The one fact about this drawing that a careful reader still gets wrong. The title block
#: has no revision field; the `D` in the side tab and the SIZE box is the sheet size. §12 Q21
#: exists purely to catch it, so we say it out loud on the front page rather than waiting to
#: be asked.
REVISION_NOTE = "Revision: none — the 'D' in the title block is the sheet size, not a revision."

#: A tile filename is generated by the extraction skill (`tile_r1c1.png`), but it reaches this
#: module from the URL, so it is treated as untrusted regardless. Names are additionally
#: checked against the manifest before anything is opened.
TILE_NAME = re.compile(r"^[A-Za-z0-9._-]{1,64}\.png$")


class DrawingUnavailable(RuntimeError):
    pass


@lru_cache(maxsize=8)
def load_circuit_logic(drawing_dir: Path) -> dict[str, Any]:
    path = drawing_dir / "circuit_logic.json"
    try:
        return json.loads(path.read_text("utf-8"))
    except FileNotFoundError as exc:
        raise DrawingUnavailable(f"no circuit_logic.json in {drawing_dir}") from exc
    except json.JSONDecodeError as exc:
        raise DrawingUnavailable(f"circuit_logic.json is not valid JSON: {exc}") from exc


def drawing_summary(drawing_dir: Path) -> dict[str, Any]:
    doc = load_circuit_logic(drawing_dir)
    meta = doc.get("drawing") or {}
    relationships = doc.get("relationships") or []

    return {
        "drawing_number": meta.get("drawing_number"),
        "title": meta.get("title"),
        "assembly": meta.get("assembly"),
        "date": meta.get("date"),
        "revision": meta.get("revision"),
        "revision_note": REVISION_NOTE if not meta.get("revision") else None,
        "proprietary_notice": meta.get("proprietary_notice"),
        "notes": meta.get("notes") or [],
        "references": meta.get("references") or [],
        "counts": {
            "components": len(doc.get("components") or []),
            "terminals": len(doc.get("terminals") or []),
            "nets": len(doc.get("nets") or []),
            "wires": len(doc.get("wires") or []),
            "cables": len(doc.get("cables") or []),
            "subsystems": len(doc.get("subsystems") or []),
            "relationships": len(relationships),
        },
        "subsystems": [
            {
                "id": s.get("id"),
                "description": s.get("description"),
                "members": len(s.get("member_components") or []),
            }
            for s in (doc.get("subsystems") or [])
        ],
        "component_classes": dict(
            sorted(Counter(c.get("class") for c in (doc.get("components") or [])).items())
        ),
        "relationship_types": dict(
            sorted(Counter(r.get("type") for r in relationships).items())
        ),
        "artifacts": _artifacts(drawing_dir),
        "source": _source_meta(drawing_dir),
        "tiles": tile_manifest(drawing_dir),
    }


def tile_manifest(drawing_dir: Path) -> dict[str, Any] | None:
    """The rendered raster of the sheet, normalised for a browser.

    `tiles/tiles.json` is written by the extraction skill and already carries everything a
    viewer needs: the page size, the DPI, and for each tile its rectangle **in PDF points**
    plus its pixel dimensions. Those points are the one coordinate system this project has —
    `components[].location` and every bbox in `geometry.json` live in the same space — so the
    rectangles are passed through unconverted and the browser does the single multiplication
    (`px = pt × dpi/72`). That is what will let a component overlay land on the drawing later
    with no registration step.

    Returns `None` unless the manifest parses, declares a positive page size, and names at
    least one PNG that is actually on disk. A half-rendered tile directory has to mean "no
    viewer", not "a viewer full of broken images".

    Deliberately uncached: it is a 4 KB parse plus one `stat` per tile, it is read once per
    page load and once per tile fetch, and a cache here would hand a stale `None` to anyone
    who renders tiles while the server is up.
    """
    tiles_dir = drawing_dir / "tiles"
    try:
        manifest = json.loads((tiles_dir / "tiles.json").read_text("utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(manifest, dict):
        return None

    size = _pair(manifest.get("page_size"))
    if size is None or size[0] <= 0 or size[1] <= 0:
        return None

    tiles = [t for t in (_tile(e, tiles_dir) for e in manifest.get("tiles") or []) if t]
    if not tiles:
        return None

    grid = manifest.get("grid") if isinstance(manifest.get("grid"), dict) else {}
    return {
        "page_size_pt": list(size),
        "dpi": manifest.get("dpi"),
        "rows": grid.get("rows"),
        "cols": grid.get("cols"),
        "count": len(tiles),
        "tiles": tiles,
    }


def tile_file(drawing_dir: Path, name: str) -> Path | None:
    """Resolve one tile by name — but only a name the manifest itself lists.

    The manifest is the allowlist. Pattern-matching the filename would already stop traversal;
    requiring the name to be a tile we published stops everything else too.
    """
    if not TILE_NAME.match(name):
        return None
    manifest = tile_manifest(drawing_dir)
    if manifest is None or not any(t["file"] == name for t in manifest["tiles"]):
        return None
    path = drawing_dir / "tiles" / name
    return path if path.is_file() else None


def _tile(entry: Any, tiles_dir: Path) -> dict[str, Any] | None:
    if not isinstance(entry, dict):
        return None
    name = entry.get("file")
    if not isinstance(name, str) or not TILE_NAME.match(name):
        return None
    if not (tiles_dir / name).is_file():
        return None

    rect = entry.get("pdf_rect")
    if not isinstance(rect, list) or len(rect) != 4:
        return None
    try:
        x0, y0, x1, y1 = (float(v) for v in rect)
    except (TypeError, ValueError):
        return None
    if x1 <= x0 or y1 <= y0:
        return None

    return {
        "file": name,
        "row": entry.get("row"),
        "col": entry.get("col"),
        "pdf_rect": [x0, y0, x1, y1],
        "pixels": _pair(entry.get("pixels")),
    }


def _pair(value: Any) -> tuple[float, float] | None:
    if not isinstance(value, list) or len(value) != 2:
        return None
    try:
        return float(value[0]), float(value[1])
    except (TypeError, ValueError):
        return None


def source_document(drawing_dir: Path) -> Path | None:
    """The PDF the netlist was extracted from, or `None` if it is not beside the extraction.

    Every extraction has the shape `<drawing>/source_docs/*.pdf` next to
    `<drawing>/extracted_docs/`, and `tiles/tiles.json` already records which file in there was
    rendered — so that name is the first choice, the drawing number is the second, and a lone
    PDF is the third. With several unrelated PDFs and nothing to disambiguate them (which is
    the state of `ModLinx/source_docs/`), this returns `None` rather than guessing.
    """
    source_dir = drawing_dir.parent / "source_docs"
    if not source_dir.is_dir():
        return None
    pdfs = sorted(p for p in source_dir.glob("*.pdf") if p.is_file())
    if not pdfs:
        return None

    for name in (_tiles_source_name(drawing_dir), _drawing_number(drawing_dir)):
        if not name:
            continue
        stem = Path(name).stem
        for pdf in pdfs:
            if pdf.stem == stem:
                return pdf
    return pdfs[0] if len(pdfs) == 1 else None


def _source_meta(drawing_dir: Path) -> dict[str, Any] | None:
    path = source_document(drawing_dir)
    if path is None:
        return None
    return {"name": path.name, "bytes": path.stat().st_size, "media_type": "application/pdf"}


def _tiles_source_name(drawing_dir: Path) -> str | None:
    try:
        manifest = json.loads((drawing_dir / "tiles" / "tiles.json").read_text("utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    name = manifest.get("source_file")
    return name if isinstance(name, str) else None


def _drawing_number(drawing_dir: Path) -> str | None:
    try:
        meta = load_circuit_logic(drawing_dir).get("drawing") or {}
    except DrawingUnavailable:
        return None
    number = meta.get("drawing_number")
    return number if isinstance(number, str) else None


def _artifacts(drawing_dir: Path) -> list[dict[str, Any]]:
    """What the model can actually see, with sizes. Shown in the UI because "which files did
    it read?" is the first question anyone sensible asks about an answer like this."""
    out = []
    for name in ("EXTRACTION_NOTES.md", "circuit_logic.json", "custom_kg.json", "geometry.json"):
        path = drawing_dir / name
        if path.exists():
            out.append({"name": name, "bytes": path.stat().st_size})
    return out
