"""`label_corrections.json` — the third authored file, and what it is *not*.

    circuit_logic.json      generated       what connects
    locations.json          authored        where it is drawn
    label_corrections.json  authored        what the ink actually says

### Why this is not part of `locations.json`

Three reasons, and each one on its own would be enough.

**It keys on a different id space.** `locations.json` keys on designators — `CR-BP`, `W052`,
`120` — the curated names in the netlist. This keys on *extraction* ids: `T0012` is one string the
OCR pass read, `C0080` is one run of ink. Neither appears in the netlist and neither ever will,
because they are one layer below it.

**It is written from a different screen.** Folding it in would widen the `K2`/`H1` window — a
whole-document save where the last writer wins — across two workflows instead of one, so a
placement run and a review run could silently discard each other. Two files, two documents, no
overlap.

**It is a different claim.** `locations.json` says *this thing is drawn here*, which is a statement
about position that a person makes by looking at the sheet. This says *the machine read this string
wrong*, which is a correction to a reading. Different claims belong in different files even when
they are edited by the same person on the same afternoon.

### What one entry says

    "labels": {
      "T0012": { "text": "L1-A",  "was": "LI-A", "by": "js", "at": "..." },
      "T0104": { "text": null,    "was": "YY",   "note": "not a net label", ... },
      "C0008": { "text": "130",   "was": null,   "by": "js", "at": "..." }
    }

`text` is the reading, and it is **required** — an entry is a decision or it is nothing. Three
things it can be:

- **a string** — this is what the ink says. `LI-A` → `L1-A`, capital I for the digit 1.
- **`null`** — *this is not a label at all.* Seven of the 34 printed net names on this sheet are
  partial reads of things that were never net names (`YY`, `U`, `+4`), and there is no string that
  says so. A blank string would mean *"I read it as empty"*, which is a different claim and is why
  `""` is refused by name.
- **the same string it already was** — *I looked, and the machine was right.* This is deliberately
  **kept**, and it is the one place this project stores something that matches the computed value.
  Invariant 10 forbids that for an end label's side, and the distinction is worth being precise
  about: a side would have been produced anyway with nobody looking, so storing it destroys the
  file's ability to tell a decision from a default. Nothing produces *confirmed* but a person. A
  low-confidence read that somebody has checked is new information, and the queue's whole job is to
  get smaller.

`was` is the reading this replaced, kept forever so a correction can be audited against what the
machine actually saw — `geometry.json` is regenerated by a re-extraction and would take the
original with it. `note` is free text for the reason.

### Where the id is checked

Not here. `parse()` validates *shape* and knows nothing about this drawing, exactly as
`locations.parse()` does; whether `T0012` is a label the ink actually holds is checked in
`resolve_corrections()`, which is handed the reduced `geometry.json`. That split matters because a
correction keyed on an id that does not exist is the one mistake a hand edit can make here **whose
symptom is nothing at all** — it is never applied, never drawn, never mentioned — so it is refused
**by name**, the same treatment and for the same reason as `H14`'s end label on a pin its wire does
not touch.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Any

from .ink import FILENAME as INK_FILENAME
from .ink import Ink, load_ink

#: One, and no migration to think about yet. A reader that meets a 2 refuses it whole rather than
#: applying half of it, which is the same rule `locations.py` has.
SCHEMA = 1
READABLE = (1,)

FILENAME = "label_corrections.json"

#: The one section. Named for what it holds rather than for the two id spaces in it, because the
#: claim is identical either way: *this is what the ink says here*.
SECTION = "labels"


class CorrectionsRefused(ValueError):
    """A write that would make the whole file meaningless. Never raised by the read path."""


@dataclass(frozen=True)
class Correction:
    """One reading a person has taken responsibility for.

    `text` is `None` for *not a label*, which is why it is not a `str` with `""` doing double duty:
    the two are different claims and only one of them is sayable in a string.
    """

    text: str | None
    was: str | None = None
    note: str | None = None
    by: str | None = None
    at: str | None = None

    @property
    def rejected(self) -> bool:
        """*This is not a label.* Kept as a property so no caller has to spell `text is None`
        and get the `""` case wrong on the way past."""
        return self.text is None

    @property
    def unchanged(self) -> bool:
        """A confirmation: somebody checked and the machine had it right."""
        return self.text is not None and self.text == self.was


@dataclass(frozen=True)
class Corrections:
    """The parsed file. `present` is *no such file* against *a file that said nothing*."""

    present: bool = False
    labels: dict[str, Correction] = field(default_factory=dict)
    problems: tuple[str, ...] = ()

    def counts(self) -> dict[str, int]:
        return {
            "corrections": len(self.labels),
            "rejections": sum(1 for c in self.labels.values() if c.rejected),
            "confirmations": sum(1 for c in self.labels.values() if c.unchanged),
        }

    def report(self) -> dict[str, Any]:
        return {"file": self.present, **self.counts(), "problems": list(self.problems)}


EMPTY = Corrections()


def corrections_path(drawing_dir: Path) -> Path:
    return drawing_dir / FILENAME


@lru_cache(maxsize=8)
def load_corrections(drawing_dir: Path) -> Corrections:
    """Parse and validate, or explain why not.

    Cached like `load_locations`, so **any writer must call `load_corrections.cache_clear()`** or it
    will save a correction and be handed the old one back. `save_corrections()` does, and is the
    only supported way to write this file from the server. That is `H2` again, in a second file.
    """
    path = corrections_path(drawing_dir)
    try:
        raw = json.loads(path.read_text("utf-8"))
    except FileNotFoundError:
        return EMPTY
    except (OSError, json.JSONDecodeError) as exc:
        return Corrections(present=True, problems=(f"{FILENAME} could not be read: {exc}",))
    return parse(raw)


def parse(raw: Any) -> Corrections:
    """Shape only. See the module docstring on why the id is checked elsewhere."""
    if not isinstance(raw, dict):
        return Corrections(present=True, problems=(f"{FILENAME} is not an object",))
    if raw.get("schema") not in READABLE:
        return Corrections(
            present=True,
            problems=(
                f"{FILENAME} declares schema {raw.get('schema')!r}, not one of {READABLE}",
            ),
        )

    problems: list[str] = []
    section = raw.get(SECTION)
    if section is None:
        return Corrections(present=True, problems=tuple(problems))
    if not isinstance(section, dict):
        problems.append(f"{SECTION} is not an object")
        return Corrections(present=True, problems=tuple(problems))

    out: dict[str, Correction] = {}
    for identifier, body in section.items():
        correction = _correction(identifier, body, problems)
        if correction is not None:
            out[identifier] = correction
    return Corrections(present=True, labels=out, problems=tuple(problems))


def _correction(identifier: Any, body: Any, problems: list[str]) -> Correction | None:
    """One entry, refused per field like everything else in this project.

    The unit is **one reading**: a malformed `T0012` costs `T0012` and leaves the other 277 alone.
    A file whose every correction is thrown away because one of them has a number in it would be
    the worst possible answer to a typo.
    """
    where = f"{SECTION}[{identifier!r}]"
    if not isinstance(identifier, str) or not identifier.strip():
        problems.append(f"{where} is not an id")
        return None
    if not isinstance(body, dict):
        problems.append(f"{where} is not an object")
        return None
    if "text" not in body:
        # Not a shape error so much as an empty claim, and the wording says which: an entry with
        # no `text` has not said anything, and the file exists to record what somebody said.
        problems.append(f"{where} says nothing: a correction needs a text, or null for not a label")
        return None

    text = body["text"]
    if text is not None and not isinstance(text, str):
        problems.append(f"{where} has text {text!r}, which is neither a string nor null")
        return None
    if isinstance(text, str) and not text.strip():
        # The one ambiguity worth refusing by name. An empty string reads as *"I read nothing
        # here"*, which is a claim about the ink; `null` means *"this is not a label"*, which is a
        # claim about the item. Letting `""` stand for either would make the file unable to say
        # the second one.
        problems.append(
            f"{where} has an empty text: use null to say this is not a label, not \"\""
        )
        return None

    for key in ("was", "note", "by", "at"):
        value = body.get(key)
        if value is not None and not isinstance(value, str):
            problems.append(f"{where} has {key} {value!r}, which is not a string")
            return None

    return Correction(
        text=text.strip() if isinstance(text, str) else None,
        was=body.get("was"),
        note=body.get("note"),
        by=body.get("by"),
        at=body.get("at"),
    )


# -- writing -------------------------------------------------------------------------------


def save_corrections(
    drawing_dir: Path, raw: Any, *, drawing_number: str | None = None
) -> Corrections:
    """Replace `label_corrections.json`, atomically, and invalidate the parse.

    The same shape of write as `save_locations` and deliberately so: whole-file, so there is no
    patch protocol to get wrong; atomic through `os.replace` in the same directory, so a reader
    sees the whole old file or the whole new one; and everything not fatal is written and *then*
    reported, so what the editor is told was refused is exactly what the next read will refuse.

    **Two refusals, not four.** A payload that is not an object, and an unknown schema — plus a
    `drawing_number` naming a different drawing, which is the mistake somebody with two tabs open
    will actually make. There is no `page_size_pt` check because there is nothing to measure: a
    correction is a string, and a string does not stop being true at a different page size. That is
    the one honest difference from `locations.json`'s write path.
    """
    if not isinstance(raw, dict):
        raise CorrectionsRefused(f"{FILENAME} must be a JSON object.")
    if raw.get("schema") not in READABLE:
        raise CorrectionsRefused(
            f"{FILENAME} declares schema {raw.get('schema')!r}; this server writes {SCHEMA}."
        )
    named = raw.get("drawing_number")
    if drawing_number and named and named != drawing_number:
        raise CorrectionsRefused(
            f"This payload is for {named!r} and the server is serving {drawing_number!r}. "
            "A reading of one sheet says nothing about another."
        )

    path = corrections_path(drawing_dir)
    body = json.dumps(raw, indent=2, ensure_ascii=False) + "\n"
    temp = path.with_name(f".{path.name}.tmp")
    try:
        temp.write_text(body, encoding="utf-8")
        os.replace(temp, path)
    finally:
        temp.unlink(missing_ok=True)

    load_corrections.cache_clear()
    return load_corrections(drawing_dir)


def skeleton(drawing_number: str | None) -> dict[str, Any]:
    """What `GET /api/review` answers for a drawing nobody has corrected anything on.

    An empty document rather than a 404, so the editor's load path has one shape — the same
    argument as `locations.skeleton`.
    """
    return {"drawing_number": drawing_number, "schema": SCHEMA, SECTION: {}}


# -- resolution ----------------------------------------------------------------------------


@dataclass(frozen=True)
class Reading:
    """One piece of ink, what the machine made of it, and what a person made of that.

    This is the record the review screen is a list of, and the record Phase E's candidate ranking
    will read instead of `geometry.json`'s raw strings. One type for both id spaces, because the
    question is the same one twice: *what does the ink say here, and how sure are we?*
    """

    id: str
    #: `label` or `conductor` — which id space, and so what `read` was read *for*.
    kind: str
    #: What the extraction settled on: a label's `text`, or a conductor's bound `net_label`.
    read: str | None
    #: What it says now, after any correction. `None` means *not a label* where a correction said
    #: so, and *never read* where nothing ever bound one.
    text: str | None
    #: 0.0–1.0 for a label. `None` for a conductor, whose net name is a *binding* rather than a
    #: read and so has no confidence to report — which is also why the queue sorts them apart.
    confidence: float | None
    #: True where the extractor put this on its own `review_queue`.
    flagged: bool
    #: The correction, when there is one. Its `was` is what makes the original auditable.
    correction: Correction | None
    #: What to frame on the sheet: a label's bbox, or the box the whole of a conductor's polyline
    #: fits in.
    rect: tuple[float, float, float, float] | None
    #: A run only: its polyline, so the screen can ring the **ink** rather than the rectangle the
    #: ink fits inside. `C0002` is a three-segment L in a 206 × 215 pt box with a dozen unrelated
    #: runs crossing it, and a ring round the box is a ring round the wrong thing. Empty on a
    #: label, which is a box and nothing else.
    points: tuple[tuple[float, float], ...] = ()
    #: A label's own guess at what sort of string it is, or a conductor's `missing` list.
    label_kind: str | None = None
    missing: tuple[str, ...] = ()
    raw_ocr: str | None = None
    #: True where correcting this changes what some conductor's net name reads as — the 70 label
    #: ids a run's net name is lifted from, and every conductor, whose reading *is* its net name.
    net_name: bool = False
    #: The runs that read their net name from this label. Empty for anything else.
    conductors: tuple[str, ...] = ()
    #: A run only: the label its net name is read from, when a correction to *that* label is what
    #: this run now reads. Absent when the run reads its own bound name or its own correction.
    via: str | None = None

    @property
    def corrected(self) -> bool:
        return self.correction is not None


def resolve_corrections(drawing_dir: Path) -> tuple[Ink, Corrections, list[Reading]]:
    """Lay the corrections over the ink, and name every correction that landed on nothing.

    The analogue of `resolve_geometry`, and the same three-layer split: `ink.reduce` knows the file
    format, `parse` knows this file's shape, and this function is the only place that knows they are
    about the same drawing. Every reading the sheet holds comes back — flagged or not — because
    *"editing all of them should be possible"* was half of the decision that produced this screen,
    and a screen that can only reach what the extractor doubted cannot fix what it was confident
    and wrong about.
    """
    ink = load_ink(drawing_dir)
    stored = load_corrections(drawing_dir)

    flagged = ink.flagged()
    missing = ink.missing_of()
    sources = ink.net_label_sources()

    problems = list(stored.problems)
    kept: dict[str, Correction] = {}
    for identifier, correction in stored.labels.items():
        if identifier in ink.labels or identifier in ink.conductors:
            kept[identifier] = correction
            continue
        # The refusal whose symptom would otherwise be nothing at all. See the module docstring.
        problems.append(
            f"{FILENAME} corrects {identifier!r}, which is not a label or a conductor in "
            f"{INK_FILENAME}"
        )

    readings: list[Reading] = []
    for label in ink.labels.values():
        correction = kept.get(label.id)
        readings.append(
            Reading(
                id=label.id,
                kind="label",
                read=label.text or None,
                text=correction.text if correction else (label.text or None),
                confidence=label.confidence,
                flagged=label.id in flagged,
                correction=correction,
                rect=label.bbox,
                label_kind=label.kind,
                raw_ocr=label.raw_ocr or None,
                net_name=label.id in sources,
                conductors=tuple(ink.conductors_of(label.id)),
            )
        )
    for conductor in ink.conductors.values():
        correction = kept.get(conductor.id)
        # **A correction to a label reaches every run that reads its net name.** Without this the
        # run would go on reading `LI-A` while the label beside it read `L1-A`, and the path matcher
        # — which compares the *run's* name against a wire's net — would be exactly as stuck as
        # before, which is the whole reason this phase comes before Phase E. A correction on the run
        # itself still wins: naming a run directly is the more specific claim, and it is the only
        # thing available for the 79 with no label bound at all.
        source = ink.net_label_source_of(conductor.id)
        via = kept.get(source) if source else None
        readings.append(
            Reading(
                id=conductor.id,
                kind="conductor",
                read=conductor.net_label,
                text=(
                    correction.text
                    if correction
                    else via.text
                    if via
                    else conductor.net_label
                ),
                via=source if via and not correction else None,
                confidence=None,
                flagged=conductor.id in flagged,
                correction=correction,
                rect=conductor.rect,
                points=conductor.points,
                missing=missing.get(conductor.id, ()),
                # A conductor's reading *is* its net name, so every one of them is on the filter
                # that matters to Phase E — including the 79 that have no name bound at all, which
                # are the ones a person can most usefully supply.
                net_name=True,
            )
        )

    resolved = Corrections(present=stored.present, labels=kept, problems=tuple(problems))
    return ink, resolved, readings


def corrected_text(readings: list[Reading]) -> dict[str, str]:
    """Every id whose ink now reads as something, after corrections — id → string.

    **This is the function Phase E's matcher reads**, and it is here rather than in that phase so
    the answer is given once. Its ranking compares a conductor's printed net name against a wire's
    net id; the whole point of Phase F is that 30 of this sheet's 70 net names were read at
    confidence 0.4 and nine of them are wrong, which is why only 17 of 26 nets match a printed
    conductor group today.

    Rejections (`text: null`) and never-read blanks are **absent** rather than empty, because a
    matcher must not compare against a string somebody said was not a name.
    """
    return {r.id: r.text for r in readings if r.text}
